;; R4RS Basic Tests - Extracted from Chicken Scheme r4rstest.scm
;; Original author: Aubrey Jaffer
;; Format: ((expression) expected-result)

;; Section 4.1.3 - Procedure calls
(((if #f + *) 3 4) 12)

;; Section 4.1.4 - Lambda
(((lambda (x) (+ x x)) 4) 8)
(((lambda x x) 3 4 5 6) (3 4 5 6))
(((lambda (x y . z) z) 3 4 5 6) (5 6))

;; Section 4.1.5 - Conditionals
((if (> 3 2) 'yes 'no) yes)
((if (> 2 3) 'yes 'no) no)
((if (> 3 2) (- 3 2) (+ 3 2)) 1)

;; Section 4.2.1 - Cond, case, and, or
((cond ((> 3 2) 'greater) ((< 3 2) 'less)) greater)
((cond ((> 3 3) 'greater) ((< 3 3) 'less) (else 'equal)) equal)
((case (* 2 3) ((2 3 5 7) 'prime) ((1 4 6 8 9) 'composite)) composite)
((and (= 2 2) (> 2 1)) #t)
((and (= 2 2) (< 2 1)) #f)
((and 1 2 'c '(f g)) (f g))
((and) #t)
((or (= 2 2) (> 2 1)) #t)
((or (= 2 2) (< 2 1)) #t)
((or #f #f #f) #f)
((or) #f)
((or (memq 'b '(a b c)) (+ 3 0)) (b c))

;; Section 4.2.2 - Let, let*, letrec
((let ((x 2) (y 3)) (* x y)) 6)
((let ((x 2) (y 3)) (let ((x 7) (z (+ x y))) (* z x))) 35)
((let ((x 2) (y 3)) (let* ((x 7) (z (+ x y))) (* z x))) 70)
((letrec ((even? (lambda (n) (if (zero? n) #t (odd? (- n 1))))) (odd? (lambda (n) (if (zero? n) #f (even? (- n 1)))))) (even? 88)) #t)

;; Section 4.2.3 - Begin
((begin (+ 1 2) (+ 3 4)) 7)

;; Section 4.2.4 - Do
((do ((vec (make-vector 5)) (i 0 (+ i 1))) ((= i 5) vec) (vector-set! vec i i)) #(0 1 2 3 4))
((let ((x '(1 3 5 7 9))) (do ((x x (cdr x)) (sum 0 (+ sum (car x)))) ((null? x) sum))) 25)

;; Named let
((let foo () 1) 1)
((let loop ((numbers '(3 -2 1 6 -5)) (nonneg '()) (neg '())) (cond ((null? numbers) (list nonneg neg)) ((negative? (car numbers)) (loop (cdr numbers) nonneg (cons (car numbers) neg))) (else (loop (cdr numbers) (cons (car numbers) nonneg) neg)))) ((6 1 3) (-5 -2)))

;; Section 4.2.6 - Quasiquote
((quasiquote (list (unquote (+ 1 2)) 4)) (list 3 4))
((let ((name 'a)) (quasiquote (list (unquote name) (quote (unquote name))))) (list a (quote a)))
((quasiquote (a (unquote (+ 1 2)) (unquote-splicing (map abs '(4 -5 6))) b)) (a 3 4 5 6 b))
((quasiquote (unquote (+ 2 3))) 5)

;; Section 6.1 - Not
((not #t) #f)
((not 3) #f)
((not (list 3)) #f)
((not #f) #t)
((not 'nil) #f)

;; Section 6.2 - Equivalence predicates
((eqv? 'a 'a) #t)
((eqv? 'a 'b) #f)
((eqv? 2 2) #t)
((eqv? '() '()) #t)
((eqv? (cons 1 2) (cons 1 2)) #f)
((eqv? #f 'nil) #f)
((eq? 'a 'a) #t)
((eq? (list 'a) (list 'a)) #f)
((eq? '() '()) #t)
((eq? car car) #t)
((equal? 'a 'a) #t)
((equal? '(a) '(a)) #t)
((equal? '(a (b) c) '(a (b) c)) #t)
((equal? "abc" "abc") #t)
((equal? 2 2) #t)
((equal? (make-vector 5 'a) (make-vector 5 'a)) #t)

;; Section 6.3 - Pairs and lists
((cons 'a '()) (a))
((cons '(a) '(b c d)) ((a) b c d))
((cons "a" '(b c)) ("a" b c))
((cons 'a 3) (a . 3))
((cons '(a b) 'c) ((a b) . c))
((car '(a b c)) a)
((car '((a) b c d)) (a))
((car '(1 . 2)) 1)
((cdr '((a) b c d)) (b c d))
((cdr '(1 . 2)) 2)
((list 'a (+ 3 4) 'c) (a 7 c))
((list) ())
((length '(a b c)) 3)
((length '(a (b) (c d e))) 3)
((length '()) 0)
((append '(x) '(y)) (x y))
((append '(a) '(b c d)) (a b c d))
((append '(a (b)) '((c))) (a (b) (c)))
((append) ())
((reverse '(a b c)) (c b a))
((reverse '(a (b c) d (e (f)))) ((e (f)) d (b c) a))
((list-ref '(a b c d) 2) c)
((memq 'a '(a b c)) (a b c))
((memq 'b '(a b c)) (b c))
((memq 'a '(b c d)) #f)
((memq (list 'a) '(b (a) c)) #f)
((member (list 'a) '(b (a) c)) ((a) c))
((memv 101 '(100 101 102)) (101 102))
((assq 'a '((a 1) (b 2) (c 3))) (a 1))
((assq 'b '((a 1) (b 2) (c 3))) (b 2))
((assq 'd '((a 1) (b 2) (c 3))) #f)
((assq (list 'a) '(((a)) ((b)) ((c)))) #f)
((assoc (list 'a) '(((a)) ((b)) ((c)))) ((a)))
((assv 5 '((2 3) (5 7) (11 13))) (5 7))

;; Section 6.4 - Symbols
((symbol? 'foo) #t)
((symbol? (car '(a b))) #t)
((symbol? "bar") #f)
((symbol? 'nil) #t)
((symbol? '()) #f)
((symbol? #f) #f)
((symbol->string 'flying-fish) "flying-fish")
((symbol->string 'Martin) "Martin")
((string->symbol "mISSISSIppi") mISSISSIppi)
((eq? 'mISSISSIppi (string->symbol "mISSISSIppi")) #t)

;; Section 6.5 - Numbers
((+ 3 4) 7)
((+ 3) 3)
((+) 0)
((* 4) 4)
((*) 1)
((- 3 4) -1)
((- 3 4 5) -6)
((- 3) -3)
((abs -7) 7)
((abs 7) 7)
((modulo 13 4) 1)
((remainder 13 4) 1)
((modulo -13 4) 3)
((remainder -13 4) -1)
((modulo 13 -4) -3)
((remainder 13 -4) 1)
((modulo -13 -4) -1)
((remainder -13 -4) -1)
((gcd 32 -36) 4)
((gcd) 0)
((lcm 32 -36) 288)
((lcm) 1)
((floor -4.3) -5.0)
((ceiling -4.3) -4.0)
((truncate -4.3) -4.0)
((round -4.3) -4.0)
((floor 3.5) 3.0)
((ceiling 3.5) 4.0)
((truncate 3.5) 3.0)
((round 3.5) 4.0)
((max 3 4) 4)
((max 3.9 4) 4)
((min 3 4) 3)
((min 3.9 4) 3.9)
((zero? 0) #t)
((zero? 1) #f)
((positive? 1) #t)
((positive? -1) #f)
((negative? -1) #t)
((negative? 1) #f)
((odd? 3) #t)
((odd? 2) #f)
((even? 2) #t)
((even? 3) #f)
((< 1 2 3) #t)
((< 1 2 2) #f)
((> 3 2 1) #t)
((> 3 2 2) #f)
((<= 1 2 2) #t)
((<= 1 2 1) #f)
((>= 3 2 2) #t)
((>= 3 2 3) #f)

;; Section 6.6 - Characters
((char? #\a) #t)
((char? 'a) #f)
((char=? #\a #\a) #t)
((char=? #\a #\b) #f)
((char<? #\a #\b) #t)
((char<? #\b #\a) #f)
((char>? #\b #\a) #t)
((char<=? #\a #\a) #t)
((char>=? #\a #\a) #t)
((char-alphabetic? #\a) #t)
((char-alphabetic? #\5) #f)
((char-numeric? #\5) #t)
((char-numeric? #\a) #f)
((char-whitespace? #\space) #t)
((char-whitespace? #\a) #f)
((char-upper-case? #\A) #t)
((char-upper-case? #\a) #f)
((char-lower-case? #\a) #t)
((char-lower-case? #\A) #f)
((char-upcase #\a) #\A)
((char-downcase #\A) #\a)
((char->integer #\a) 97)
((integer->char 97) #\a)

;; Section 6.7 - Strings
((string? "abc") #t)
((string? 'abc) #f)
((make-string 3 #\a) "aaa")
((string #\a #\b #\c) "abc")
((string-length "abc") 3)
((string-ref "abc" 1) #\b)
((string=? "abc" "abc") #t)
((string=? "abc" "abd") #f)
((string<? "abc" "abd") #t)
((string>? "abd" "abc") #t)
((string<=? "abc" "abc") #t)
((string>=? "abc" "abc") #t)
((substring "abcdef" 2 5) "cde")
((string-append "abc" "def") "abcdef")
((string-append) "")
((string->list "abc") (#\a #\b #\c))
((list->string '(#\a #\b #\c)) "abc")

;; Section 6.8 - Vectors
((vector? (vector 1 2 3)) #t)
((vector? '(1 2 3)) #f)
((make-vector 3 'a) #(a a a))
((vector 'a 'b 'c) #(a b c))
((vector-length (vector 'a 'b 'c)) 3)
((vector-ref (vector 'a 'b 'c) 1) b)
((vector->list (vector 'a 'b 'c)) (a b c))
((list->vector '(a b c)) #(a b c))

;; Section 6.9 - Procedures
((procedure? car) #t)
((procedure? 'car) #f)
((procedure? (lambda (x) (* x x))) #t)
((apply + '(1 2 3)) 6)
((apply + 1 2 '(3 4)) 10)
((map + '(1 2 3) '(4 5 6)) (5 7 9))
((map car '((a b) (d e) (g h))) (a d g))
