/* The following code was generated by JFlex 1.4.2 on 4/6/26, 6:54 PM */

package net.sourceforge.kleinlisp.parser;

import java_cup.runtime.*;
import net.sourceforge.kleinlisp.*;
import net.sourceforge.kleinlisp.objects.CharObject;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 4/6/26, 6:54 PM from the specification file
 * <tt>src/main/java/net/sourceforge/kleinlisp/parser/lexical.flex</tt>
 */
class LexicalAnalyzer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int END = 6;
  public static final int BARRED_SYMBOL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\53\1\13\2\0\1\12\22\0\1\52\1\7\1\15\1\14"+
    "\1\7\1\7\1\0\1\17\1\23\1\24\1\7\1\6\1\21\1\1"+
    "\1\4\1\7\1\3\11\2\1\10\1\54\1\7\1\7\1\7\1\7"+
    "\1\22\4\51\1\5\1\51\24\7\1\25\1\31\1\26\1\0\1\7"+
    "\1\20\1\34\1\42\1\35\1\47\1\11\1\30\2\7\1\41\1\7"+
    "\1\46\1\40\1\45\1\36\1\7\1\33\1\7\1\43\1\32\1\27"+
    "\1\44\1\7\1\37\1\50\2\7\1\0\1\16\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\1\4\1\5\2\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\22\1\24\1\25"+
    "\1\24\1\26\1\27\1\0\1\30\1\31\1\32\1\0"+
    "\1\33\1\0\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\0\1\47\3\50"+
    "\1\0\6\50\2\0\1\27\11\0\1\51\1\52\1\0"+
    "\1\53\13\0\1\54\4\0\1\55\1\56\4\0\1\57"+
    "\2\0\1\60\1\61\1\62\2\0\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u0168\0\u0168\0\u0195\0\264\0\u01c2\0\264\0\264\0\264"+
    "\0\264\0\u01ef\0\264\0\264\0\264\0\264\0\u021c\0\u0249"+
    "\0\264\0\264\0\u0276\0\u02a3\0\264\0\u02d0\0\264\0\u02fd"+
    "\0\u032a\0\264\0\264\0\264\0\u0357\0\264\0\u0384\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\u03b1\0\u03de\0\264\0\u040b\0\u0438\0\u0465"+
    "\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd"+
    "\0\u05cd\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708"+
    "\0\u0735\0\u0762\0\u0573\0\264\0\u078f\0\264\0\u07bc\0\u07e9"+
    "\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951"+
    "\0\u097e\0\264\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\264\0\264"+
    "\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\264\0\u0b13\0\u0b40\0\264"+
    "\0\264\0\264\0\u0b6d\0\u0b9a\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\5\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\5\1\23"+
    "\1\24\1\25\1\26\2\12\1\5\20\12\2\14\1\27"+
    "\12\30\1\31\1\0\1\30\1\32\13\30\1\33\21\30"+
    "\1\31\1\30\16\34\1\35\12\34\1\36\23\34\55\37"+
    "\57\0\1\7\1\10\53\0\2\7\1\40\54\0\1\40"+
    "\51\0\11\12\15\0\2\12\1\0\20\12\16\0\1\14"+
    "\51\0\1\41\12\0\1\42\3\0\1\43\1\44\1\45"+
    "\45\0\1\46\32\0\12\27\2\0\41\27\12\30\2\0"+
    "\1\30\1\0\13\30\1\0\21\30\1\0\1\30\2\0"+
    "\2\47\11\0\1\50\1\0\1\51\7\0\1\52\1\0"+
    "\1\53\4\0\1\54\4\0\1\55\11\0\16\34\1\0"+
    "\12\34\1\0\23\34\16\0\1\56\10\0\1\57\1\0"+
    "\1\60\4\0\1\61\4\0\1\62\13\0\2\40\1\0"+
    "\1\63\3\0\1\63\47\0\6\64\15\0\2\64\1\0"+
    "\20\64\3\0\11\65\1\66\15\65\1\67\2\65\1\70"+
    "\1\65\1\71\1\65\1\72\3\65\1\73\1\74\3\65"+
    "\1\75\1\76\4\65\2\0\2\77\52\0\1\100\2\101"+
    "\2\0\1\100\47\0\11\64\15\0\2\64\1\0\20\64"+
    "\35\0\1\102\56\0\1\103\53\0\1\104\61\0\1\105"+
    "\25\0\1\106\32\0\1\107\44\0\1\110\31\0\1\111"+
    "\54\0\1\112\45\0\2\113\1\0\1\113\3\0\1\113"+
    "\16\0\1\113\3\0\2\113\4\0\1\113\4\0\1\113"+
    "\1\0\1\113\5\0\2\114\53\0\2\101\106\0\1\115"+
    "\61\0\1\116\46\0\1\117\54\0\1\120\57\0\1\121"+
    "\55\0\1\122\51\0\1\123\46\0\1\124\65\0\1\125"+
    "\50\0\1\126\55\0\1\127\62\0\1\130\51\0\1\131"+
    "\54\0\1\132\62\0\1\133\52\0\1\134\21\0\1\135"+
    "\76\0\1\136\32\0\1\137\110\0\1\140\50\0\1\141"+
    "\45\0\1\142\65\0\1\143\40\0\1\144\36\0\1\145"+
    "\101\0\1\146\51\0\1\147\57\0\1\150\27\0\1\151"+
    "\54\0\1\152\77\0\1\153\55\0\1\154\30\0\1\155"+
    "\43\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3015];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\6\1\1\11\1\1\4\11\1\1\4\11"+
    "\2\1\2\11\2\1\1\11\1\1\1\11\1\1\1\0"+
    "\3\11\1\0\1\11\1\0\13\11\1\0\1\1\1\11"+
    "\2\1\1\0\6\1\2\0\1\1\11\0\1\1\1\11"+
    "\1\0\1\11\13\0\1\11\4\0\2\11\4\0\1\11"+
    "\2\0\3\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private void error(){    
    throw new SyntaxError(String.format("Unrecognizable token: '%s' at line %d, column %d", yytext(), yyline, yycolumn));
}

private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn);
}

private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value);
}
StringBuilder str = new StringBuilder();
StringBuilder barredSymbol = new StringBuilder();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { str.setLength(0); yybegin(STRING);
          }
        case 52: break;
        case 45: 
          { return symbol( sym.CHAR_LITERAL, new CharObject(' ') );
          }
        case 53: break;
        case 8: 
          { barredSymbol.setLength(0); yybegin(BARRED_SYMBOL);
          }
        case 54: break;
        case 13: 
          { return symbol( sym.CLOSE_PAR );
          }
        case 55: break;
        case 35: 
          { barredSymbol.append('\t');
          }
        case 56: break;
        case 23: 
          { return symbol( sym.DOUBLE_LITERAL,  Double.parseDouble(yytext()) );
          }
        case 57: break;
        case 11: 
          { return symbol( sym.UNQUOTE );
          }
        case 58: break;
        case 20: 
          { barredSymbol.append(yytext());
          }
        case 59: break;
        case 34: 
          { barredSymbol.append('|');
          }
        case 60: break;
        case 36: 
          { barredSymbol.append('\\');
          }
        case 61: break;
        case 38: 
          { barredSymbol.append('\r');
          }
        case 62: break;
        case 47: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\033') );
          }
        case 63: break;
        case 21: 
          { yybegin(YYINITIAL); return symbol(sym.ATOM, barredSymbol.toString());
          }
        case 64: break;
        case 40: 
          { return symbol( sym.CHAR_LITERAL, new CharObject(yytext().charAt(2)) );
          }
        case 65: break;
        case 46: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\007') );
          }
        case 66: break;
        case 19: 
          { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL, str.toString());
          }
        case 67: break;
        case 6: 
          { /* whitespace */
          }
        case 68: break;
        case 10: 
          { return symbol( sym.QUASIQUOTE );
          }
        case 69: break;
        case 30: 
          { str.append('\t');
          }
        case 70: break;
        case 49: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\177') );
          }
        case 71: break;
        case 24: 
          { return symbol( sym.VECTOR_OPEN );
          }
        case 72: break;
        case 25: 
          { return symbol( sym.BOOL_LITERAL, true );
          }
        case 73: break;
        case 26: 
          { return symbol( sym.BOOL_LITERAL, false );
          }
        case 74: break;
        case 42: 
          { String s = yytext().substring(1);
		s = "" + ((char) Integer.parseInt(s));
		str.append( s );
          }
        case 75: break;
        case 17: 
          { str.append( yytext() );
          }
        case 76: break;
        case 3: 
          { return symbol( sym.INT_LITERAL,  Integer.parseInt(yytext()) );
          }
        case 77: break;
        case 15: 
          { return symbol( sym.CLOSE_BRACKET );
          }
        case 78: break;
        case 5: 
          { return symbol( sym.ATOM,  yytext() );
          }
        case 79: break;
        case 31: 
          { str.append('\\');
          }
        case 80: break;
        case 51: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\b') );
          }
        case 81: break;
        case 37: 
          { barredSymbol.append('\n');
          }
        case 82: break;
        case 33: 
          { str.append('\r');
          }
        case 83: break;
        case 18: 
          { /* Malformed string */
          }
        case 84: break;
        case 27: 
          { return symbol( sym.UNQUOTE_SPLICING );
          }
        case 85: break;
        case 9: 
          { return symbol( sym.QUOTE );
          }
        case 86: break;
        case 28: 
          { str.append('\"');
          }
        case 87: break;
        case 12: 
          { return symbol( sym.OPEN_PAR );
          }
        case 88: break;
        case 44: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\0') );
          }
        case 89: break;
        case 2: 
          { return symbol( sym.ATOM, "-" );
          }
        case 90: break;
        case 1: 
          { error();
          }
        case 91: break;
        case 50: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\n') );
          }
        case 92: break;
        case 39: 
          { return symbol( sym.KEYWORD, yytext().substring(2) );
          }
        case 93: break;
        case 16: 
          { /* single-line comment */
          }
        case 94: break;
        case 29: 
          { str.append('\'');
          }
        case 95: break;
        case 48: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\r') );
          }
        case 96: break;
        case 4: 
          { return symbol( sym.DOT );
          }
        case 97: break;
        case 43: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\t') );
          }
        case 98: break;
        case 14: 
          { return symbol( sym.OPEN_BRACKET );
          }
        case 99: break;
        case 41: 
          { String hex = yytext().substring(3);
        int codepoint = Integer.parseInt(hex, 16);
        return symbol( sym.CHAR_LITERAL, new CharObject((char) codepoint) );
          }
        case 100: break;
        case 22: 
          { 
          }
        case 101: break;
        case 32: 
          { str.append('\n');
          }
        case 102: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
