/* The following code was generated by JFlex 1.4.2 on 4/3/26, 5:43 PM */

package net.sourceforge.kleinlisp.parser;

import java_cup.runtime.*;
import net.sourceforge.kleinlisp.*;
import net.sourceforge.kleinlisp.objects.CharObject;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 4/3/26, 5:43 PM from the specification file
 * <tt>src/main/java/net/sourceforge/kleinlisp/parser/lexical.flex</tt>
 */
class LexicalAnalyzer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int END = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\52\1\13\2\0\1\12\22\0\1\51\1\7\1\15\1\14"+
    "\1\7\1\7\1\0\1\16\1\22\1\23\1\7\1\6\1\20\1\1"+
    "\1\4\1\7\1\3\11\2\1\10\1\53\1\7\1\7\1\7\1\7"+
    "\1\21\4\50\1\5\1\50\24\7\1\24\1\30\1\25\1\0\1\7"+
    "\1\17\1\33\1\41\1\34\1\46\1\11\1\27\2\7\1\40\1\7"+
    "\1\45\1\37\1\44\1\35\1\7\1\32\1\7\1\42\1\31\1\26"+
    "\1\43\1\7\1\36\1\47\2\7\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\1\5\2\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\21\1\23\1\24\1\0"+
    "\1\25\1\26\1\0\1\27\1\0\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\0\1\36\3\37\1\0\6\37"+
    "\2\0\1\24\11\0\1\40\1\41\1\0\1\42\13\0"+
    "\1\43\4\0\1\44\1\45\4\0\1\46\2\0\1\47"+
    "\1\50\1\51\2\0\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0134\0\u0160\0\204\0\u018c\0\204\0\204\0\204\0\u01b8"+
    "\0\204\0\204\0\204\0\204\0\u01e4\0\u0210\0\204\0\204"+
    "\0\u023c\0\204\0\u0268\0\u0294\0\204\0\204\0\u02c0\0\204"+
    "\0\u02ec\0\204\0\204\0\204\0\204\0\204\0\204\0\u0318"+
    "\0\u0344\0\204\0\u0370\0\u039c\0\u03c8\0\u03f4\0\u0420\0\u044c"+
    "\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u0528\0\u0554\0\u0580"+
    "\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u04d0"+
    "\0\204\0\u06e0\0\204\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc"+
    "\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898\0\u08c4\0\204\0\u08f0"+
    "\0\u091c\0\u0948\0\u0974\0\204\0\204\0\u09a0\0\u09cc\0\u09f8"+
    "\0\u0a24\0\204\0\u0a50\0\u0a7c\0\204\0\204\0\204\0\u0aa8"+
    "\0\u0ad4\0\204";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\5\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\4\1\21\1\22"+
    "\1\23\1\24\2\11\1\4\20\11\2\13\1\25\12\26"+
    "\1\27\1\0\1\26\1\30\12\26\1\31\21\26\1\27"+
    "\1\26\54\32\56\0\1\6\1\7\52\0\2\6\1\33"+
    "\53\0\1\33\50\0\11\11\14\0\2\11\1\0\20\11"+
    "\16\0\1\13\50\0\1\34\15\0\1\35\1\36\1\37"+
    "\44\0\1\40\32\0\12\25\2\0\40\25\12\26\2\0"+
    "\1\26\1\0\12\26\1\0\21\26\1\0\1\26\2\0"+
    "\2\41\11\0\1\42\1\43\7\0\1\44\1\0\1\45"+
    "\4\0\1\46\4\0\1\47\13\0\2\33\1\0\1\50"+
    "\3\0\1\50\46\0\6\51\14\0\2\51\1\0\20\51"+
    "\3\0\11\52\1\53\14\52\1\54\2\52\1\55\1\52"+
    "\1\56\1\52\1\57\3\52\1\60\1\61\3\52\1\62"+
    "\1\63\4\52\2\0\2\64\51\0\1\65\2\66\2\0"+
    "\1\65\46\0\11\51\14\0\2\51\1\0\20\51\34\0"+
    "\1\67\55\0\1\70\52\0\1\71\60\0\1\72\25\0"+
    "\1\73\31\0\1\74\43\0\1\75\31\0\1\76\53\0"+
    "\1\77\44\0\2\100\1\0\1\100\3\0\1\100\15\0"+
    "\1\100\3\0\2\100\4\0\1\100\4\0\1\100\1\0"+
    "\1\100\5\0\2\101\52\0\2\66\104\0\1\102\60\0"+
    "\1\103\45\0\1\104\53\0\1\105\56\0\1\106\54\0"+
    "\1\107\50\0\1\110\45\0\1\111\64\0\1\112\47\0"+
    "\1\113\54\0\1\114\61\0\1\115\50\0\1\116\53\0"+
    "\1\117\61\0\1\120\51\0\1\121\21\0\1\122\74\0"+
    "\1\123\32\0\1\124\106\0\1\125\47\0\1\126\44\0"+
    "\1\127\64\0\1\130\37\0\1\131\36\0\1\132\77\0"+
    "\1\133\50\0\1\134\56\0\1\135\27\0\1\136\53\0"+
    "\1\137\75\0\1\140\54\0\1\141\30\0\1\142\42\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2816];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\6\1\1\11\1\1\3\11\1\1\4\11"+
    "\2\1\2\11\1\1\1\11\1\1\1\0\2\11\1\0"+
    "\1\11\1\0\6\11\1\0\1\1\1\11\2\1\1\0"+
    "\6\1\2\0\1\1\11\0\1\1\1\11\1\0\1\11"+
    "\13\0\1\11\4\0\2\11\4\0\1\11\2\0\3\11"+
    "\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private void error(){    
    throw new SyntaxError(String.format("Unrecognizable token: '%s' at line %d, column %d", yytext(), yyline, yycolumn));
}

private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn);
}

private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value);
}
StringBuilder str = new StringBuilder();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { str.setLength(0); yybegin(STRING);
          }
        case 43: break;
        case 36: 
          { return symbol( sym.CHAR_LITERAL, new CharObject(' ') );
          }
        case 44: break;
        case 12: 
          { return symbol( sym.CLOSE_PAR );
          }
        case 45: break;
        case 20: 
          { return symbol( sym.DOUBLE_LITERAL,  Double.parseDouble(yytext()) );
          }
        case 46: break;
        case 10: 
          { return symbol( sym.UNQUOTE );
          }
        case 47: break;
        case 38: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\033') );
          }
        case 48: break;
        case 31: 
          { return symbol( sym.CHAR_LITERAL, new CharObject(yytext().charAt(2)) );
          }
        case 49: break;
        case 37: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\007') );
          }
        case 50: break;
        case 18: 
          { yybegin(YYINITIAL); return symbol(sym.STRING_LITERAL, str.toString());
          }
        case 51: break;
        case 6: 
          { /* whitespace */
          }
        case 52: break;
        case 9: 
          { return symbol( sym.QUASIQUOTE );
          }
        case 53: break;
        case 26: 
          { str.append('\t');
          }
        case 54: break;
        case 40: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\177') );
          }
        case 55: break;
        case 21: 
          { return symbol( sym.BOOL_LITERAL, true );
          }
        case 56: break;
        case 22: 
          { return symbol( sym.BOOL_LITERAL, false );
          }
        case 57: break;
        case 33: 
          { String s = yytext().substring(1);
		s = "" + ((char) Integer.parseInt(s));
		str.append( s );
          }
        case 58: break;
        case 16: 
          { str.append( yytext() );
          }
        case 59: break;
        case 3: 
          { return symbol( sym.INT_LITERAL,  Integer.parseInt(yytext()) );
          }
        case 60: break;
        case 14: 
          { return symbol( sym.CLOSE_BRACKET );
          }
        case 61: break;
        case 5: 
          { return symbol( sym.ATOM,  yytext() );
          }
        case 62: break;
        case 27: 
          { str.append('\\');
          }
        case 63: break;
        case 42: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\b') );
          }
        case 64: break;
        case 29: 
          { str.append('\r');
          }
        case 65: break;
        case 17: 
          { /* Malformed string */
          }
        case 66: break;
        case 23: 
          { return symbol( sym.UNQUOTE_SPLICING );
          }
        case 67: break;
        case 8: 
          { return symbol( sym.QUOTE );
          }
        case 68: break;
        case 24: 
          { str.append('\"');
          }
        case 69: break;
        case 11: 
          { return symbol( sym.OPEN_PAR );
          }
        case 70: break;
        case 2: 
          { return symbol( sym.ATOM, "-" );
          }
        case 71: break;
        case 1: 
          { error();
          }
        case 72: break;
        case 35: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\0') );
          }
        case 73: break;
        case 41: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\n') );
          }
        case 74: break;
        case 30: 
          { return symbol( sym.KEYWORD, yytext().substring(2) );
          }
        case 75: break;
        case 15: 
          { /* single-line comment */
          }
        case 76: break;
        case 25: 
          { str.append('\'');
          }
        case 77: break;
        case 39: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\r') );
          }
        case 78: break;
        case 4: 
          { return symbol( sym.DOT );
          }
        case 79: break;
        case 34: 
          { return symbol( sym.CHAR_LITERAL, new CharObject('\t') );
          }
        case 80: break;
        case 13: 
          { return symbol( sym.OPEN_BRACKET );
          }
        case 81: break;
        case 19: 
          { 
          }
        case 82: break;
        case 28: 
          { str.append('\n');
          }
        case 83: break;
        case 32: 
          { String hex = yytext().substring(3);
        int codepoint = Integer.parseInt(hex, 16);
        return symbol( sym.CHAR_LITERAL, new CharObject((char) codepoint) );
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
