
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 15 20:59:48 CET 2026
//----------------------------------------------------

package net.sourceforge.kleinlisp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_PAR = 6;
  public static final int DOUBLE_LITERAL = 12;
  public static final int CLOSE_PAR = 7;
  public static final int BOOL_LITERAL = 13;
  public static final int INT_LITERAL = 11;
  public static final int STRING_LITERAL = 3;
  public static final int EOF = 0;
  public static final int ATOM = 2;
  public static final int OPEN_BRACKET = 8;
  public static final int DOT = 10;
  public static final int CLOSE_BRACKET = 9;
  public static final int error = 1;
  public static final int QUOTE = 5;
  public static final int KEYWORD = 4;
}

