//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 05 18:49:13 CEST 2019
//----------------------------------------------------

package net.sourceforge.kleinlisp.parser;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {
    /* terminals */
    public static final int OPEN_PAR = 5;
    public static final int DOUBLE_LITERAL = 10;
    public static final int CLOSE_PAR = 6;
    public static final int INT_LITERAL = 9;
    public static final int STRING_LITERAL = 3;
    public static final int EOF = 0;
    public static final int ATOM = 2;
    public static final int OPEN_BRACKET = 7;
    public static final int CLOSE_BRACKET = 8;
    public static final int error = 1;
    public static final int QUOTE = 4;
}

