
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 27 21:01:54 CET 2026
//----------------------------------------------------

package net.sourceforge.kleinlisp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 12;
  public static final int UNQUOTE_SPLICING = 8;
  public static final int BOOL_LITERAL = 16;
  public static final int QUASIQUOTE = 6;
  public static final int ATOM = 2;
  public static final int OPEN_BRACKET = 11;
  public static final int QUOTE = 5;
  public static final int STRING_LITERAL = 3;
  public static final int INT_LITERAL = 14;
  public static final int OPEN_PAR = 9;
  public static final int KEYWORD = 4;
  public static final int EOF = 0;
  public static final int CHAR_LITERAL = 17;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int UNQUOTE = 7;
  public static final int CLOSE_PAR = 10;
  public static final int DOUBLE_LITERAL = 15;
}

